### ISSUE TITLE
When incoming lat and long is NULL, the geopoint field in node should also be NULL

### ISSUE THREAD

**Issue by ComLock** [runarmyklebust/xploader#7]
![screen shot 2017-04-27 at 16 31 52](https://cloud.githubusercontent.com/assets/118847/25488607/bcac0a66-2b67-11e7-918e-01b47c675ae6.png)

Example: LOCATION_ID 1300678

**Comment by runarmyklebust** [comment]
fixed in 0e30ebe64d8ae1df678f652192b59c2e2925ec37
